
public class Euler2 {
	
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		long a = 1; 
		long b = 2; 
		long c = 0; 
		long max = 4000000; 
		long count = 0;
		//long i = 0; 
		
		//the while loop could be changed to while true but I left it the way it was in case I missed a break :)
		while ( a < max || b < max || c < max) {
		
			//System.out.println(a); 
			if (a % 2 == 0){
				//System.out.println(a);
				if (a >= max) {
					break;
				}
				count += a; 
			}
			//System.out.println(b);
			if (b % 2 == 0){
				//System.out.println(b);
				if (b >= max) {
					break;
				}
				count += b; 
			}
			c = a + b;
			//System.out.println(c); 
			if (c % 2 == 0){
				//System.out.println(c);
				if (c >= max) {
					break;
				}
				count += c; 
			}
			a = b + c; 
			b = a + c; 
			//i++; 
		}
		System.out.println("The sum of the even Fibonacci numbers up to "+ max +" is: " + count); 
	}

}
